services:
  prometheus:
    image: prom/prometheus:v3.12.0
    container_name: healthcare-prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
    networks:
      - healthcare-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:13.0.1-security-01
    container_name: healthcare-grafana
    volumes:
      - grafana_data:/var/lib/grafana
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - healthcare-network
    depends_on:
      - prometheus

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  healthcare-network:
    external: true