scrape_configs:
  - job_name: healthcare-backend
    scrape_interval: 10s
    static_configs:
      - targets:
          - backend-1.healthcare.internal:8080
          - backend-2.healthcare.internal:8080
          - backend-3.healthcare.internal:8080
  - job_name: node
    scrape_interval: 10s
    static_configs:
      - targets:
          - monitoring.healthcare.internal:9100
          - backend-1.healthcare.internal:9100
          - backend-2.healthcare.internal:9100
          - backend-3.healthcare.internal:9100
          - postgres.healthcare.internal:9100