services:
  backend:
    image: mmizu/healthcare-backend
    ports:
      - "8080:${SERVER_PORT}"
    env_file:
      - ../env/app.env
    networks:
      - healthcare-network
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8080/healthz" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter
    pid: host
    ports:
      - "9100:9100"
    networks:
      - healthcare-network
    restart: unless-stopped

networks:
  healthcare-network:
    external: true